### ISSUE TITLE
JobQueue

### ISSUE THREAD

**Issue by agbankar** [PrakharSrivastav/workers#1]
Nice code , we are planning to implement this in our project . I am pretty much new to GoLang.

How does JobQueue works .
Is it a queue where all workers submits their JobChan. If it is so then JobQueue has a capacity of 10 or its capacity less . Please suggest

**Comment by agbankar** [comment]
Got it

Thanks

**Comment by PrakharSrivastav** [comment]
Sorry for the late reply. Cool that you figured it out.
